all:
	make -C ex00
	make -C ex01
	make -C ex02
	make -C ex03


fclean:
	make fclean -C ex00
	make fclean -C ex01
	make fclean -C ex02
	make fclean -C ex03


run:
	make run -C ex00
	make run -C ex01
	make run -C ex02
	make run -C ex03

re:
	make re -C ex00
	make re -C ex01
	make re -C ex02
	make re -C ex03
