all:
	make -C ex00
	make -C ex01
	make -C ex02
	make -C ex03
	make -C ex04
	make -C ex05
	make -C ex06

fclean:
	make fclean -C ex00
	make fclean -C ex01
	make fclean -C ex02
	make fclean -C ex03
	make fclean -C ex04
	make fclean -C ex05
	make fclean -C ex06

run:
	make run -C ex00
	make run -C ex01
	make run -C ex02
	make run -C ex03
	make run -C ex04
	make run -C ex05
	make run -C ex06
re:
	make re -C ex00
	make re -C ex01
	make re -C ex02
	make re -C ex03
	make re -C ex04
	make re -C ex05
	make re -C ex06